post http://localhost:3000/products
Content-Type: application/json

{
 "title": "Uri's Shawarma Wheel",
 "description": "Passed down from generation to generation, from one Uri to another, the legends say that the fifth Uri who held the wheel was originally Jacob., know as U.S.W",
 "price": 999999,
 "category": "food",
 "image": "https://res.cloudinary.com/dbfsp3hfk/image/upload/v1732008081/pexels-rdne-5779371_fkpyib.jpg",
 "rating": 4.9
}

###

GET http://localhost:3000/products
Content-Type: application/json

###

GET http://localhost:3000/products/categories
Content-Type: application/json